custom:
  customFields:
    -
      name: "name"
      value: "My Name"
    -
      name: "site"
      value: "My Site"

routing:
  default:
    inputTopic: syslog, syslog-two
    outputTopic: syslog-unknown
  rules:
    -
      regEx: ".*%FTD-6-43000[1-5].*"
      outputTopic: "syslog-ips-cisco"
    -
      regEx: ".*%FTD-6-302014.*"
      outputTopic: "syslog-ips-other"