custom:
  customFields:
    -
      name: "rccName"
      value: "RCC-K"
    -
      name: "siteName"
      value: "Walker"

routing:
  default:
    inputTopic: syslog
    outputTopic: syslog-unknown
  rules:
    -
      regEx: ".*%FTD-6-43000[1-5].*"
      outputTopic: "syslog-ips-cisco"
    -
      regEx: ".*%FTD-6-302014.*"
      outputTopic: "syslog-ips-other"